version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      timezone: "America/Los_Angeles"
  - package-ecosystem: "npm"
    directory: "/server"
    schedule:
      interval: "daily"
      timezone: "America/Los_Angeles"
